## basic pandas, load dataset dan ide numpy

In [61]:
## load dataset
import numpy as np
import pandas as pd

In [62]:
dataframe = pd.read_csv("../datasets/hotel_bookings.csv")

In [63]:
dataframe

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [64]:
df_shape = pd.DataFrame([dataframe.shape], columns=['jumlah baris', 'jumlah kolom'])
df_shape

   jumlah baris  jumlah kolom
0        119390            32

In [65]:
dataframe.shape

(119390, 32)

In [66]:
dataframe.head(12)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.0,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.0,0,0,Check-Out,2015-07-05

In [67]:
dataframe.tail(3)
#kalo head kan kepala, ini ekornya, jadi dimulai dari akhirnya

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [68]:
dataframe.sample(5)
#jadi dia mengambil secara acak barisnya untuk sample

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
60920,City Hotel,1,0,2016,November,48,25,2,2,2,...,No Deposit,28.0,NaN,0,Transient,105.00,0,0,Canceled,2016-11-25
44531,City Hotel,0,97,2015,October,41,7,0,2,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.00,0,1,Check-Out,2015-10-09
116794,City Hotel,0,4,2017,July,29,22,2,1,2,...,No Deposit,9.0,NaN,0,Transient,160.00,0,2,Check-Out,2017-07-25
18181,Resort Hotel,0,0,2015,November,46,9,1,1,1,...,No Deposit,NaN,NaN,0,Transient,53.00,0,0,Check-Out,2015-11-11
22269,Resort Hotel,0,10,2016,March,12,19,2,1,2,...,No Deposit,240.0,NaN,0,Transient,71.33,0,1,Check-Out,2016-03-22

In [69]:

#melihat kolom ajajaa
df_clumns = pd.DataFrame(dataframe.columns, columns=["jumlah kolom yang aziz punya"])
df_clumns

      jumlah kolom yang aziz punya
0                            hotel
1                      is_canceled
2                        lead_time
3                arrival_date_year
4               arrival_date_month
5         arrival_date_week_number
6        arrival_date_day_of_month
7          stays_in_weekend_nights
8             stays_in_week_nights
9                           adults
10                        children
11                          babies
12                            meal
13                         country
14                  market_segment
15            distribution_channel
16               is_repeated_guest
17          previous_cancellations
18  previous_bookings_not_canceled
19              reserved_room_type
20              assigned_room_type
21                 booking_changes
22                    deposit_type
23                           agent
24                         company
25            days_in_waiting_list
26                   customer_type
27                             adr
28     required_car_parking_spaces
29       total_of_special_requests
30              reservation_status
31         reservation_status_date

In [70]:
df_type = pd.DataFrame(dataframe.dtypes, columns=['jumlah tipe data'])
df_type

                               jumlah tipe data
hotel                                    object
is_canceled                               int64
lead_time                                 int64
arrival_date_year                         int64
arrival_date_month                       object
arrival_date_week_number                  int64
arrival_date_day_of_month                 int64
stays_in_weekend_nights                   int64
stays_in_week_nights                      int64
adults                                    int64
children                                float64
babies                                    int64
meal                                     object
country                                  object
market_segment                           object
distribution_channel                     object
is_repeated_guest                         int64
previous_cancellations                    int64
previous_bookings_not_canceled            int64
reserved_room_type                       object
assigned_room_type                       object
booking_changes                           int64
deposit_type                             object
agent                                   float64
company                                 float64
days_in_waiting_list                      int64
customer_type                            object
adr                                     float64
required_car_parking_spaces               int64
total_of_special_requests                 int64
reservation_status                       object
reservation_status_date                  object

In [71]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [72]:
dataframe['agent'].dtype
#cek tipe data

dtype('float64')

In [73]:
dataframe['agent'].isna().sum()
#cek berapa jumlah nilai kosong

np.int64(16340)

In [74]:
dataframe['adr']
#cekk nilai kosong

0           0.00
1           0.00
2          75.00
3          75.00
4          98.00
           ...
119385     96.14
119386    225.43
119387    157.71
119388    104.40
119389    151.20
Name: adr, Length: 119390, dtype: float64

In [75]:
dataframe.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

## data celaenig

In [76]:
dataframe.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [77]:
#kita ubah ke persenatasi
dataframe.isna().sum() / len(dataframe) * 100

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
adults                             0.000000
children                           0.003350
babies                             0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [78]:
# mengisi datanya -> Unknown -> .fillna()
dataframe['agent'] = dataframe['agent'].fillna('unknown')
dataframe['country'] = dataframe['country'].fillna('unknown')

In [79]:
dataframe.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                                0
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                                  0
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

##
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Jumlah per kolom (axis=0, default)
print(df.sum(axis=0))
# Output:
# A     6
# B    15

# Jumlah per baris (axis=1)
print(df.sum(axis=1))
# Output:
# 0     5   (1+4)
# 1     7   (2+5)
# 2     9   (3+6)

## karena pas di jadikan fram jadi a dan b bukan a b keawah kayak di kode

import pandas as pd

df = pd.DataFrame({
    'A': [1,2,3],
    'B': [4,5,6],
    'C': [7,8,9]
})

# Hapus baris dengan index 0
df_drop_row = df.drop(0, axis=0)
print(df_drop_row)
# Output: baris pertama hilang

# Hapus kolom 'B'
df_drop_col = df.drop('B', axis=1)
print(df_drop_col)
# Output: kolom B hilang

In [80]:
dataframe.head(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,unknown,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,unknown,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,unknown,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [81]:
dataframenew = dataframe.drop(columns=['company'], axis=1)

In [82]:
dataframenew.isna().sum()
dataframenew.head(2)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01

In [83]:
df_colom_test = pd.DataFrame(dataframenew.columns, columns=['test column'])
df_colom_test

                       test column
0                            hotel
1                      is_canceled
2                        lead_time
3                arrival_date_year
4               arrival_date_month
5         arrival_date_week_number
6        arrival_date_day_of_month
7          stays_in_weekend_nights
8             stays_in_week_nights
9                           adults
10                        children
11                          babies
12                            meal
13                         country
14                  market_segment
15            distribution_channel
16               is_repeated_guest
17          previous_cancellations
18  previous_bookings_not_canceled
19              reserved_room_type
20              assigned_room_type
21                 booking_changes
22                    deposit_type
23                           agent
24            days_in_waiting_list
25                   customer_type
26                             adr
27     required_car_parking_spaces
28       total_of_special_requests
29              reservation_status
30         reservation_status_date

In [84]:
# cek duplikat data
dataframenew.duplicated().sum()

np.int64(32001)

In [85]:
dataframenew[dataframenew.duplicated].head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,1,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,0,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07
138,Resort Hotel,1,5,2015,July,28,5,1,0,2,...,0,No Deposit,240.0,0,Transient,97.00,0,0,Canceled,2015-07-01
200,Resort Hotel,0,0,2015,July,28,7,0,1,1,...,0,No Deposit,240.0,0,Transient,109.80,0,3,Check-Out,2015-07-08

In [86]:
# drop duplicat
dataframenew.drop_duplicates(inplace=True)

In [87]:
dataframenew.duplicated().sum()

np.int64(0)

In [88]:
# df.groupby()
dataframenew.groupby("hotel")["is_canceled"].value_counts().unstack()

is_canceled       0      1
hotel
City Hotel    37377  16049
Resort Hotel  25987   7976

In [89]:
df_clumns

      jumlah kolom yang aziz punya
0                            hotel
1                      is_canceled
2                        lead_time
3                arrival_date_year
4               arrival_date_month
5         arrival_date_week_number
6        arrival_date_day_of_month
7          stays_in_weekend_nights
8             stays_in_week_nights
9                           adults
10                        children
11                          babies
12                            meal
13                         country
14                  market_segment
15            distribution_channel
16               is_repeated_guest
17          previous_cancellations
18  previous_bookings_not_canceled
19              reserved_room_type
20              assigned_room_type
21                 booking_changes
22                    deposit_type
23                           agent
24                         company
25            days_in_waiting_list
26                   customer_type
27                             adr
28     required_car_parking_spaces
29       total_of_special_requests
30              reservation_status
31         reservation_status_date

In [90]:
dataframenew.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,unknown,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [91]:
dataframenew.groupby('hotel')['adr'].mean()

hotel
City Hotel      110.985270
Resort Hotel     99.030296
Name: adr, dtype: float64

In [92]:
dataframenew.groupby(['arrival_date_year', 'hotel'])['adr'].mean().unstack()

hotel              City Hotel  Resort Hotel
arrival_date_year
2015                89.813927     94.450802
2016               107.896446     90.653587
2017               121.986516    113.020094

In [93]:
dataframenew.groupby('customer_type')['lead_time'].aggregate(['min', 'max', 'count', 'mean'])

                 min  max  count        mean
customer_type
Contract           0  532   3139  109.225231
Group              0  468    544   51.584559
Transient          0  737  71982   73.431274
Transient-Party    0  542  11724  113.057489

In [94]:
dataframenew.head(2)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01


## feature engineering

In [95]:
dataframenew['total_nights'] = dataframenew['stays_in_weekend_nights'] + dataframenew['stays_in_week_nights']

In [96]:
dataframenew[['total_nights', 'stays_in_weekend_nights', 'stays_in_week_nights']].head(15)

    total_nights  stays_in_weekend_nights  stays_in_week_nights
0              0                        0                     0
1              0                        0                     0
2              1                        0                     1
3              1                        0                     1
4              2                        0                     2
6              2                        0                     2
7              2                        0                     2
8              3                        0                     3
9              3                        0                     3
10             4                        0                     4
11             4                        0                     4
12             4                        0                     4
13             4                        0                     4
14             4                        0                     4
15             4                        0                     4

In [97]:
dataframenew.head(1)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,unknown,0,Transient,0.0,0,0,Check-Out,2015-07-01,0

In [98]:
df_columnsnew = pd.DataFrame(dataframenew.columns, columns=['colom baru'])

In [99]:
df_columnsnew

                        colom baru
0                            hotel
1                      is_canceled
2                        lead_time
3                arrival_date_year
4               arrival_date_month
5         arrival_date_week_number
6        arrival_date_day_of_month
7          stays_in_weekend_nights
8             stays_in_week_nights
9                           adults
10                        children
11                          babies
12                            meal
13                         country
14                  market_segment
15            distribution_channel
16               is_repeated_guest
17          previous_cancellations
18  previous_bookings_not_canceled
19              reserved_room_type
20              assigned_room_type
21                 booking_changes
22                    deposit_type
23                           agent
24            days_in_waiting_list
25                   customer_type
26                             adr
27     required_car_parking_spaces
28       total_of_special_requests
29              reservation_status
30         reservation_status_date
31                    total_nights

In [100]:
dataframenew['is_repeated_guest_category'] = dataframenew['is_repeated_guest'].apply(lambda x:'yes' if x== 1 else 'no')

In [101]:
dataframenew[['is_repeated_guest_category','is_repeated_guest' ]].sample(12)

       is_repeated_guest_category  is_repeated_guest
97363                          no                  0
59246                          no                  0
105297                         no                  0
72297                          no                  0
4991                           no                  0
26354                          no                  0
102989                         no                  0
13438                          no                  0
93716                          no                  0
101173                         no                  0
37512                          no                  0
22369                          no                  0

In [102]:
dataframenew.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                              object
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
total_nights                        int64
is_repeated_guest_category         object
dtype: object

In [103]:
dataframenew['reservation_status_date'] = pd.to_datetime(dataframenew['reservation_status_date'])#string to bject datetime
# Mengekstrak nama bulan dari tanggal tersebut.
dataframenew['month_of_reservation_status'] = dataframenew['reservation_status_date'].dt.month_name()

dataframenew[['month_of_reservation_status','reservation_status_date']].sample(7)

       month_of_reservation_status reservation_status_date
31846                      January              2017-01-08
111880                         May              2017-05-17
104187                     January              2017-01-08
103190                    December              2016-12-15
45499                      October              2015-10-06
94697                       August              2016-08-08
107021                       March              2017-03-06

In [104]:
dataframenew['reservation_status_date']

0        2015-07-01
1        2015-07-01
2        2015-07-02
3        2015-07-02
4        2015-07-03
            ...
119385   2017-09-06
119386   2017-09-07
119387   2017-09-07
119388   2017-09-07
119389   2017-09-07
Name: reservation_status_date, Length: 87389, dtype: datetime64[ns]

In [105]:
dataframenew['arrival_date_month']

0           July
1           July
2           July
3           July
4           July
           ...
119385    August
119386    August
119387    August
119388    August
119389    August
Name: arrival_date_month, Length: 87389, dtype: object

In [106]:
#map
month_mapping = {
    'January': 1, 'February': 2, 'March': 3,
    'April': 4, 'May': 5, 'June': 6,
    'July': 7, 'August': 8, 'September': 9,
    'October': 10, 'November': 11, 'December': 12
}
dataframenew['arrival_date_month'] = dataframenew['arrival_date_month'].map(month_mapping)

In [107]:
dataframenew['arrival_date_month']

0         7
1         7
2         7
3         7
4         7
         ..
119385    8
119386    8
119387    8
119388    8
119389    8
Name: arrival_date_month, Length: 87389, dtype: int64

### (boolean) -> lamda, (multiclas) -> map
### DataFrameNew['arrival_in_jan'] = DataFrameNew['arrival_date_month'].apply(lambda x: 1 if x == 'January' else 0)
### DataFrameNew['arrival_in_jan'].sample(10)

In [108]:
dataframenew.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87389 entries, 0 to 119389
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87389 non-null  object
 1   is_canceled                     87389 non-null  int64
 2   lead_time                       87389 non-null  int64
 3   arrival_date_year               87389 non-null  int64
 4   arrival_date_month              87389 non-null  int64
 5   arrival_date_week_number        87389 non-null  int64
 6   arrival_date_day_of_month       87389 non-null  int64
 7   stays_in_weekend_nights         87389 non-null  int64
 8   stays_in_week_nights            87389 non-null  int64
 9   adults                          87389 non-null  int64
 10  children                        87385 non-null  float64
 11  babies                          87389 non-null  int64
 12  meal                            87389 non-null  object
 13  country                         87389 non-null  object
 14  market_segment                  87389 non-null  object
 15  distribution_channel            87389 non-null  object
 16  is_repeated_guest               87389 non-null  int64
 17  previous_cancellations          87389 non-null  int64
 18  previous_bookings_not_canceled  87389 non-null  int64
 19  reserved_room_type              87389 non-null  object
 20  assigned_room_type              87389 non-null  object
 21  booking_changes                 87389 non-null  int64
 22  deposit_type                    87389 non-null  object
 23  agent                           87389 non-null  object
 24  days_in_waiting_list            87389 non-null  int64
 25  customer_type                   87389 non-null  object
 26  adr                             87389 non-null  float64
 27  required_car_parking_spaces     87389 non-null  int64
 28  total_of_special_requests       87389 non-null  int64
 29  reservation_status              87389 non-null  object
 30  reservation_status_date         87389 non-null  datetime64[ns]
 31  total_nights                    87389 non-null  int64
 32  is_repeated_guest_category      87389 non-null  object
 33  month_of_reservation_status     87389 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(18), object(13)
memory usage: 23.3+ MB

# Advanced Data Preprocessing

In [109]:
dataframenew

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,is_repeated_guest_category,month_of_reservation_status
0,Resort Hotel,0,342,2015,7,27,1,0,0,2,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,0,no,July
1,Resort Hotel,0,737,2015,7,27,1,0,0,2,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,0,no,July
2,Resort Hotel,0,7,2015,7,27,1,0,1,1,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,1,no,July
3,Resort Hotel,0,13,2015,7,27,1,0,1,1,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,1,no,July
4,Resort Hotel,0,14,2015,7,27,1,0,2,2,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,2,no,July
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,8,35,30,2,5,2,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,7,no,September
119386,City Hotel,0,102,2017,8,35,31,2,5,3,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,7,no,September
119387,City Hotel,0,34,2017,8,35,31,2,5,2,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,7,no,September
119388,City Hotel,0,109,2017,8,35,31,2,5,2,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,7,no,September
119389,City Hotel,0,205,2017,8,35,29,2,7,2,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,9,no,September

In [110]:
dataframenew.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87389 entries, 0 to 119389
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87389 non-null  object
 1   is_canceled                     87389 non-null  int64
 2   lead_time                       87389 non-null  int64
 3   arrival_date_year               87389 non-null  int64
 4   arrival_date_month              87389 non-null  int64
 5   arrival_date_week_number        87389 non-null  int64
 6   arrival_date_day_of_month       87389 non-null  int64
 7   stays_in_weekend_nights         87389 non-null  int64
 8   stays_in_week_nights            87389 non-null  int64
 9   adults                          87389 non-null  int64
 10  children                        87385 non-null  float64
 11  babies                          87389 non-null  int64
 12  meal                            87389 non-null  object
 13  country                         87389 non-null  object
 14  market_segment                  87389 non-null  object
 15  distribution_channel            87389 non-null  object
 16  is_repeated_guest               87389 non-null  int64
 17  previous_cancellations          87389 non-null  int64
 18  previous_bookings_not_canceled  87389 non-null  int64
 19  reserved_room_type              87389 non-null  object
 20  assigned_room_type              87389 non-null  object
 21  booking_changes                 87389 non-null  int64
 22  deposit_type                    87389 non-null  object
 23  agent                           87389 non-null  object
 24  days_in_waiting_list            87389 non-null  int64
 25  customer_type                   87389 non-null  object
 26  adr                             87389 non-null  float64
 27  required_car_parking_spaces     87389 non-null  int64
 28  total_of_special_requests       87389 non-null  int64
 29  reservation_status              87389 non-null  object
 30  reservation_status_date         87389 non-null  datetime64[ns]
 31  total_nights                    87389 non-null  int64
 32  is_repeated_guest_category      87389 non-null  object
 33  month_of_reservation_status     87389 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(18), object(13)
memory usage: 23.3+ MB

In [111]:
numerical_columns = dataframenew.select_dtypes(include=['float64', 'int64']).columns.to_list()

## remove outlier atau anomali

In [112]:
def remove_outlier_iqr(df, columns, x):
    df_clean = df.copy()
    for col in columns:
        q1 = df_clean[col].quantile(0.25)
        q3 = df_clean[col].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - x * iqr #1.5
        upper_bound = q3 + x * iqr #1.5
        df_clean = df_clean[(df_clean[col] >= lower_bound) & (df_clean[col] <= upper_bound)] 
    return df_clean

In [113]:
df_no_outliers = remove_outlier_iqr(dataframenew, numerical_columns, 2)

In [114]:
df_no_outliers

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,is_repeated_guest_category,month_of_reservation_status
4,Resort Hotel,0,14,2015,7,27,1,0,2,2,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,2,no,July
6,Resort Hotel,0,0,2015,7,27,1,0,2,2,...,0,Transient,107.00,0,0,Check-Out,2015-07-03,2,no,July
7,Resort Hotel,0,9,2015,7,27,1,0,2,2,...,0,Transient,103.00,0,1,Check-Out,2015-07-03,2,no,July
8,Resort Hotel,1,85,2015,7,27,1,0,3,2,...,0,Transient,82.00,0,1,Canceled,2015-05-06,3,no,May
9,Resort Hotel,1,75,2015,7,27,1,0,3,2,...,0,Transient,105.50,0,0,Canceled,2015-04-22,3,no,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119383,City Hotel,0,164,2017,8,35,31,2,4,2,...,0,Transient,87.60,0,0,Check-Out,2017-09-06,6,no,September
119384,City Hotel,0,21,2017,8,35,30,2,5,2,...,0,Transient,96.14,0,2,Check-Out,2017-09-06,7,no,September
119385,City Hotel,0,23,2017,8,35,30,2,5,2,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,7,no,September
119388,City Hotel,0,109,2017,8,35,31,2,5,2,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,7,no,September
119389,City Hotel,0,205,2017,8,35,29,2,7,2,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,9,no,September

In [115]:
from sklearn.preprocessing import MinMaxScaler
df_min_max_scaler = df_no_outliers.copy()
min_max_scaler = MinMaxScaler()
df_min_max_scaler[numerical_columns] = min_max_scaler.fit_transform(df_no_outliers[numerical_columns])

In [116]:
df_min_max_scaler.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,total_nights
count,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.0,41261.0,...,41261.0,41261.0,41261.0,41261.0,41261.0,41261.000000,41261.0,41261.000000,41261,41261.000000
mean,0.313928,0.229555,0.612358,0.492358,0.491423,0.491488,0.254902,0.289714,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.441003,0.0,0.233449,2016-09-01 10:51:01.234579712,0.329730
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,2014-11-18 00:00:00,0.000000
25%,0.000000,0.050992,0.500000,0.272727,0.288462,0.233333,0.000000,0.111111,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.328947,0.0,0.000000,2016-03-22 00:00:00,0.181818
50%,0.000000,0.161473,0.500000,0.454545,0.500000,0.500000,0.250000,0.222222,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.422368,0.0,0.333333,2016-09-09 00:00:00,0.272727
75%,1.000000,0.354108,1.000000,0.727273,0.692308,0.766667,0.500000,0.444444,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.548246,0.0,0.333333,2017-03-06 00:00:00,0.454545
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,1.000000,2017-09-10 00:00:00,1.000000
std,0.464093,0.219232,0.341510,0.276257,0.258283,0.295602,0.227818,0.181627,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.170556,0.0,0.259930,NaN,0.193688

In [117]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [118]:
df_standardscaler = df_no_outliers.copy()
df_standardscaler[numerical_columns] = std_scaler.fit_transform(df_no_outliers[numerical_columns])

In [119]:
df_standardscaler.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,total_nights
count,4.126100e+04,4.126100e+04,4.126100e+04,4.126100e+04,4.126100e+04,4.126100e+04,4.126100e+04,4.126100e+04,41261.0,41261.0,...,41261.0,41261.0,41261.0,41261.0,41261.0,4.126100e+04,41261.0,4.126100e+04,41261,4.126100e+04
mean,5.786151e-17,-8.610343e-17,1.066746e-13,6.474978e-17,-1.226113e-16,-9.919115e-17,-1.289829e-16,-1.208462e-16,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.124876e-16,0.0,3.478579e-17,2016-09-01 10:51:01.234579712,-3.917706e-17
min,-6.764420e-01,-1.047101e+00,-1.793112e+00,-1.782269e+00,-1.902676e+00,-1.662688e+00,-1.118894e+00,-1.595124e+00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-2.585707e+00,0.0,-8.981326e-01,2014-11-18 00:00:00,-1.702403e+00
25%,-6.764420e-01,-8.145065e-01,-3.290075e-01,-7.950333e-01,-7.858194e-01,-8.733283e-01,-1.118894e+00,-9.833618e-01,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-6.570109e-01,0.0,-8.981326e-01,2016-03-22 00:00:00,-7.636727e-01
50%,-6.764420e-01,-3.105521e-01,-3.290075e-01,-1.368761e-01,3.320895e-02,2.879747e-02,-2.151618e-02,-3.716000e-01,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-1.092612e-01,0.0,3.842791e-01,2016-09-09 00:00:00,-2.943074e-01
75%,1.478323e+00,5.681378e-01,1.135097e+00,8.503595e-01,7.777801e-01,9.309232e-01,1.075862e+00,8.519237e-01,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.287865e-01,0.0,3.842791e-01,2017-03-06 00:00:00,6.444231e-01
max,1.478323e+00,3.514333e+00,1.135097e+00,1.837595e+00,1.969094e+00,1.720283e+00,3.270618e+00,3.910733e+00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.277529e+00,0.0,2.949102e+00,2017-09-10 00:00:00,3.460615e+00
std,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000012e+00,0.0,1.000012e+00,NaN,1.000012e+00

In [120]:
from sklearn.preprocessing import RobustScaler
robust_scaler = RobustScaler()
df_robust_sclaer = df_no_outliers.copy()
df_robust_sclaer[numerical_columns] = robust_scaler.fit_transform(df_no_outliers[numerical_columns])

In [121]:
df_robust_sclaer.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,total_nights
count,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.000000,41261.0,41261.0,...,41261.0,41261.0,41261.0,41261.0,41261.0,41261.000000,41261.0,41261.000000,41261,41261.000000
mean,0.313928,0.224607,0.224716,0.083188,-0.021239,-0.015961,0.009803,0.202475,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.084975,0.0,-0.299653,2016-09-01 10:51:01.234579712,0.209011
min,0.000000,-0.532710,-1.000000,-1.000000,-1.238095,-0.937500,-0.500000,-0.666667,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-1.926000,0.0,-1.000000,2014-11-18 00:00:00,-1.000000
25%,0.000000,-0.364486,0.000000,-0.400000,-0.523810,-0.500000,-0.500000,-0.333333,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.426000,0.0,-1.000000,2016-03-22 00:00:00,-0.333333
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,2016-09-09 00:00:00,0.000000
75%,1.000000,0.635514,1.000000,0.600000,0.476190,0.500000,0.500000,0.666667,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.574000,0.0,0.000000,2017-03-06 00:00:00,0.666667
max,1.000000,2.766355,1.000000,1.200000,1.238095,0.937500,1.500000,2.333333,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.634000,0.0,2.000000,2017-09-10 00:00:00,2.666667
std,0.464093,0.723261,0.683019,0.607765,0.639558,0.554253,0.455637,0.544881,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.777737,0.0,0.779790,NaN,0.710188

In [122]:
dataframenew[numerical_columns].corr()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,total_nights
is_canceled,1.000000,0.184772,0.088021,0.003735,0.001469,0.005317,0.060159,0.082886,0.081775,0.067382,-0.020548,-0.089654,0.051464,-0.052160,-0.093664,0.004461,0.127974,-0.184224,-0.120567,0.084059
lead_time,0.184772,1.000000,0.139123,0.106216,0.101195,0.009852,0.235109,0.310088,0.140439,0.028618,-0.003620,-0.147021,0.005369,-0.078941,0.077005,0.132151,0.023533,-0.086564,0.034213,0.318228
arrival_date_year,0.088021,0.139123,1.000000,-0.499849,-0.514194,-0.010073,0.005127,0.003623,0.038573,0.041132,-0.023338,0.024339,-0.054217,0.027255,0.008596,-0.027943,0.176063,-0.039816,0.064246,0.004607
arrival_date_month,0.003735,0.106216,-0.499849,1.000000,0.995084,0.000827,0.027150,0.031778,0.027170,0.013665,0.014119,-0.037727,0.007546,-0.021713,0.011751,0.012763,0.103543,0.007330,0.049607,0.033754
arrival_date_week_number,0.001469,0.101195,-0.514194,0.995084,1.000000,0.093641,0.026901,0.027842,0.024429,0.013469,0.014265,-0.036853,0.007202,-0.020816,0.011919,0.013847,0.098341,0.008959,0.046622,0.030735
arrival_date_day_of_month,0.005317,0.009852,-0.010073,0.000827,0.093641,1.000000,-0.017801,-0.028216,-0.001143,0.015802,-0.000395,-0.004181,-0.008540,0.000150,0.006300,0.006587,0.022597,0.009162,-0.001667,-0.027615
stays_in_weekend_nights,0.060159,0.235109,0.005127,0.027150,0.026901,-0.017801,1.000000,0.555543,0.088232,0.028542,0.013663,-0.106963,-0.020641,-0.056660,0.050297,-0.031685,0.038926,-0.042938,0.032365,0.786258
stays_in_week_nights,0.082886,0.310088,0.003623,0.031778,0.027842,-0.028216,0.555543,1.000000,0.095519,0.030456,0.016002,-0.113562,-0.018788,-0.058513,0.085020,0.001899,0.053285,-0.044327,0.037809,0.950575
adults,0.081775,0.140439,0.038573,0.027170,0.024429,-0.001143,0.088232,0.095519,1.000000,0.023700,0.016634,-0.171739,-0.042106,-0.120928,-0.048093,-0.015746,0.248939,0.007780,0.112755,0.103930
children,0.067382,0.028618,0.041132,0.013665,0.013469,0.015802,0.028542,0.030456,0.023700,1.000000,0.017419,-0.045659,-0.019211,-0.029428,0.031299,-0.020422,0.326299,0.036321,0.044600,0.033291
babies,-0.020548,-0.003620,-0.023338,0.014119,0.014265,-0.000395,0.013663,0.016002,0.016634,0.017419,1.000000,-0.012979,-0.005395,-0.009193,0.081032,-0.006840,0.023444,0.030882,0.094821,0.016994
is_repeated_guest,-0.089654,-0.147021,0.024339,-0.037727,-0.036853,-0.004181,-0.106963,-0.113562,-0.171739,-0.045659,-0.012979,1.000000,0.206373,0.441455,0.006041,-0.012817,-0.153056,0.072015,-0.001326,-0.124333
previous_cancellations,0.051464,0.005369,-0.054217,0.007546,0.007202,-0.008540,-0.020641,-0.018788,-0.042106,-0.019211,-0.005395,0.206373,1.000000,0.392064,-0.010271,0.003681,-0.050273,-0.003401,0.001869,-0.021670
previous_bookings_not_canceled,-0.052160,-0.078941,0.027255,-0.021713,-0.020816,0.000150,-0.056660,-0.058513,-0.120928,-0.029428,-0.009193,0.441455,0.392064,1.000000,0.005417,-0.006304,-0.085730,0.040869,0.027110,-0.064641
booking_changes,-0.093664,0.077005,0.008596,0.011751,0.011919,0.006300,0.050297,0.085020,-0.048093,0.031299,0.081032,0.006041,-0.010271,0.005417,1.000000,0.024202,0.002540,0.048709,0.016106,0.081962
days_in_waiting_list,0.004461,0.132151,-0.027943,0.012763,0.013847,0.006587,-0.031685,0.001899,-0.015746,-0.020422,-0.006840,-0.012817,0.003681,-0.006304,0.024202,1.000000,-0.033006,-0.016069,-0.049548,-0.010421
adr,0.127974,0.023533,0.176063,0.103543,0.098341,0.022597,0.038926,0.053285,0.248939,0.326299,0.023444,-0.153056,-0.050273,-0.085730,0.002540,-0.033006,1.000000,0.039111,0.137804,0.054134
required_car_parking_spaces,-0.184224,-0.086564,-0.039816,0.007330,0.008959,0.009162,-0.042938,-0.044327,0.007780,0.036321,0.030882,0.072015,-0.003401,0.040869,0.048709,-0.016069,0.039111,1.000000,0.048448,-0.048975
total_of_special_requests,-0.120567,0.034213,0.064246,0.049607,0.046622,-0.001667,0.032365,0.037809,0.112755,0.044600,0.094821,-0.001326,0.001869,0.027110,0.016106,-0.049548,0.137804,0.048448,1.000000,0.040183
total_nights,0.084059,0.318228,0.004607,0.033754,0.030735,-0.027615,0.786258,0.950575,0.103930,0.033291,0.016994,-0.124333,-0.021670,-0.064641,0.081962,-0.010421,0.054134,-0.048975,0.040183,1.000000