In [212]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [213]:
dataframe = pd.read_csv("../datasets/iris.csv")

In [214]:
dataframe['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [215]:
dataframe.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [216]:
dataframe.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [217]:
dataframe.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [218]:
iris_data_numeric = dataframe[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values

In [219]:
python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)

In [220]:
print(python_list)
print(array_from_list)

[1, 2, 3, 4, 5]
[1 2 3 4 5]

In [221]:
print(array_from_list[2])

3

In [222]:
zeroz_array = np.zeros((3,3,3))
zeroz_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [223]:
ones_array = np.ones((4, 4, 4))
ones_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [224]:
# np.arange() -> similar with for loop (start, stop, step?) for i in range
arage_array = np.arange(0, 30, 5)
arage_array

array([ 0,  5, 10, 15, 20, 25])

In [225]:
random_float = np.random.rand(5, 5)
random_float

array([[0.79467569, 0.1563145 , 0.83096644, 0.38620245, 0.03325839],
       [0.46865704, 0.12497796, 0.69738326, 0.56973131, 0.6515334 ],
       [0.89165431, 0.34501602, 0.62494881, 0.43072924, 0.91257124],
       [0.11475742, 0.0364174 , 0.83818444, 0.45316032, 0.29444189],
       [0.45877615, 0.63574865, 0.17337156, 0.61497626, 0.1609954 ]])

In [226]:
random_int = np.random.randint(0, 23, size=(4, 4))
random_int

array([[22, 13,  8, 15],
       [11,  7,  4, 14],
       [15,  2, 12,  8],
       [19, 21,  1,  9]], dtype=int32)

## reshape array

In [227]:
old_array = np.arange(2, 14)
old_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [228]:
array_reshape = old_array.reshape(3, 4)
array_reshape

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

## indexing dan slicing

In [229]:
iris_data_numeric[0, 0]

np.float64(5.1)

In [230]:
dataframe.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [231]:
# [row, column] 
iris_data_numeric[0:5, 0:3]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [232]:
iris_data_numeric[:, -3:]

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.1, 1.5, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3, 0.3],
       [3.2, 1.3, 0.2],
       [3.5, 1.6, 0.6],
       [3.8, 1.9, 0.4],
       [3. , 1.4, 0.3],
       [3.8, 1.6, 0.2],
       [3.2, 1.4, 0.2],
       [3.7, 1.5, 0.2],
       [3.3, 1.4, 0.2],
       [3.2, 4.7, 1.4],
       [3.2, 4.5, 1.5],
       [3.1, 4.9, 1.5],
       [2.3, 4. , 1.3],
       [2.8, 4.6, 1.5],
       [2.8, 4.5, 1.3],
       [3.3, 4.7, 1.6],
       [2.4, 3.3, 1. ],
       [2.9, 4.6, 1.3],
       [2.7, 3.9, 1.4],
       [2. , 3.5, 1. ],
       [3. , 4.2, 1.5],
       [2.2, 4. , 1. ],
       [2.9, 4.7, 1.4],
       [2.9, 3.6, 1.3],
       [3.1, 4.4, 1.4],
       [3. , 4.5, 1.5],
       [2.7, 4.1, 1. ],
       [2.2, 4.5, 1.5],
       [2.5, 3.9, 1.1],
       [3.2, 4.8, 1.8],
       [2.8, 4. , 1.3],
       [2.5, 4.9, 1.5],
       [2.8, 4.7, 1.2],
       [2.9, 4.3, 1.3],
       [3. , 4.4, 1.4],
       [2.8, 4.8, 1.4],
       [3. , 5. , 1.7],
       [2.9, 4.5, 1.5],
       [2.6, 3.5, 1. ],
       [2.4, 3.8, 1.1],
       [2.4, 3.7, 1. ],
       [2.7, 3.9, 1.2],
       [2.7, 5.1, 1.6],
       [3. , 4.5, 1.5],
       [3.4, 4.5, 1.6],
       [3.1, 4.7, 1.5],
       [2.3, 4.4, 1.3],
       [3. , 4.1, 1.3],
       [2.5, 4. , 1.3],
       [2.6, 4.4, 1.2],
       [3. , 4.6, 1.4],
       [2.6, 4. , 1.2],
       [2.3, 3.3, 1. ],
       [2.7, 4.2, 1.3],
       [3. , 4.2, 1.2],
       [2.9, 4.2, 1.3],
       [2.9, 4.3, 1.3],
       [2.5, 3. , 1.1],
       [2.8, 4.1, 1.3],
       [3.3, 6. , 2.5],
       [2.7, 5.1, 1.9],
       [3. , 5.9, 2.1],
       [2.9, 5.6, 1.8],
       [3. , 5.8, 2.2],
       [3. , 6.6, 2.1],
       [2.5, 4.5, 1.7],
       [2.9, 6.3, 1.8],
       [2.5, 5.8, 1.8],
       [3.6, 6.1, 2.5],
       [3.2, 5.1, 2. ],
       [2.7, 5.3, 1.9],
       [3. , 5.5, 2.1],
       [2.5, 5. , 2. ],
       [2.8, 5.1, 2.4],
       [3.2, 5.3, 2.3],
       [3. , 5.5, 1.8],
       [3.8, 6.7, 2.2],
       [2.6, 6.9, 2.3],
       [2.2, 5. , 1.5],
       [3.2, 5.7, 2.3],
       [2.8, 4.9, 2. ],
       [2.8, 6.7, 2. ],
       [2.7, 4.9, 1.8],
       [3.3, 5.7, 2.1],
       [3.2, 6. , 1.8],
       [2.8, 4.8, 1.8],
       [3. , 4.9, 1.8],
       [2.8, 5.6, 2.1],
       [3. , 5.8, 1.6],
       [2.8, 6.1, 1.9],
       [3.8, 6.4, 2. ],
       [2.8, 5.6, 2.2],
       [2.8, 5.1, 1.5],
       [2.6, 5.6, 1.4],
       [3. , 6.1, 2.3],
       [3.4, 5.6, 2.4],
       [3.1, 5.5, 1.8],
       [3. , 4.8, 1.8],
       [3.1, 5.4, 2.1],
       [3.1, 5.6, 2.4],
       [3.1, 5.1, 2.3],
       [2.7, 5.1, 1.9],
       [3.2, 5.9, 2.3],
       [3.3, 5.7, 2.5],
       [3. , 5.2, 2.3],
       [2.5, 5. , 1.9],
       [3. , 5.2, 2. ],
       [3.4, 5.4, 2.3],
       [3. , 5.1, 1.8]])

Berikut penjelasan dalam format **Markdown (MD)** tentang **indexing dan slicing di NumPy** supaya lebih rapi dan mudah dipahami:

---

# 🧩 Indexing & Slicing di NumPy

NumPy menyediakan cara fleksibel untuk mengambil sebagian data dari array menggunakan **indexing** dan **slicing**.

## 📌 Indexing
- Digunakan untuk mengambil **elemen tertentu** dari array.
- Indeks dimulai dari **0**.
- Bisa menggunakan indeks positif (dari depan) atau negatif (dari belakang).

Contoh:
```python
arr = np.array([10, 20, 30, 40])
print(arr[0])   # 10 (elemen pertama)
print(arr[-1])  # 40 (elemen terakhir)
```

## 📌 Slicing
- Digunakan untuk mengambil **sebagian range** dari array.
- Format umum: `array[start:stop:step]`
  - `start` → indeks awal (default = 0)
  - `stop` → indeks akhir (tidak termasuk)
  - `step` → langkah (default = 1)

Contoh:
```python
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[::2])    # [10 30 50]
```

## 📌 Slicing pada Array 2D/3D
Gunakan format `array[baris, kolom]`.

Contoh dengan array 2D:
```python
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0, 0])     # 1 (baris 0, kolom 0)
print(mat[0:2, 1:3]) # [[2 3]
                     #  [5 6]]
```

Contoh dengan array 3D:
```python
cube = np.zeros((3, 3, 3))

print(cube[0, :, :])   # ambil "lapisan" pertama
print(cube[:, -1, :])  # ambil baris terakhir dari semua lapisan
```

## 📌 Contoh Praktis dengan Dataset Iris
```python
from sklearn.datasets import load_iris
iris = load_iris()
iris_data_numeric = iris.data  # shape (150, 4)

# 5 baris pertama, 2 kolom pertama
print(iris_data_numeric[0:5, 0:2])

# Semua baris, 2 kolom terakhir
print(iris_data_numeric[:, -2:])

# Semua baris, hanya kolom ke-2 dari belakang
print(iris_data_numeric[:, -2])
```

---

👉 Ringkasnya:
- **Indexing** → ambil elemen spesifik.
- **Slicing** → ambil range elemen.
- Bisa digabung untuk array multidimensi: `[baris, kolom]`.

---

Mau saya tambahkan juga tabel ringkas perbedaan `arr[:, -2]` vs `arr[:, -2:]` biar lebih gampang diingat?

In [233]:
dataframe['sepal_length']
dataframe

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [234]:
sepal_lenghth = iris_data_numeric[iris_data_numeric[:, 0] > 5.0]
sepal_lenghth

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

## operasi array aritmatika agregation

In [235]:
data15 = np.arange(1, 6)
data15

array([1, 2, 3, 4, 5])

In [236]:
data510 = np.arange(6, 11)
data510

array([ 6,  7,  8,  9, 10])

In [237]:
data510.shape

(5,)

In [238]:
data15.shape

(5,)

In [239]:
data_sum = data15 * 5
data_sum

array([ 5, 10, 15, 20, 25])

In [240]:
data_suubtrac = data510 - data15
data_suubtrac

array([5, 5, 5, 5, 5])

In [241]:
data = np.random.randint(10, 100, size=(3, 3))
data

array([[74, 29, 27],
       [62, 72, 82],
       [36, 95, 14]], dtype=int32)

In [242]:
data_sqrt = np.sqrt(data)
data_sqrt

array([[8.60232527, 5.38516481, 5.19615242],
       [7.87400787, 8.48528137, 9.05538514],
       [6.        , 9.74679434, 3.74165739]])

In [243]:
data_log = np.log(data)
data_log

array([[4.30406509, 3.36729583, 3.29583687],
       [4.12713439, 4.27666612, 4.40671925],
       [3.58351894, 4.55387689, 2.63905733]])

In [244]:
data_log2 = np.log2(data)
data_log2

array([[6.20945337, 4.857981  , 4.7548875 ],
       [5.95419631, 6.169925  , 6.357552  ],
       [5.169925  , 6.56985561, 3.80735492]])

## dot product dan matrix multiplication

In [245]:
v1 = np.array([1, 5, 6])
v2 = np.array([3, 5, 6])

In [246]:
hasilnpdot = np.dot(v1, v2)
hasilnpdot

np.int64(64)

In [251]:
m1 = np.array([[1, 3, 5], 
             [2, 4, 6]])

m2 = np.array([[6, 3], 
               [2, 9],
               [2, 4]])

In [252]:
hasildot = np.dot(m1 , m2)
hasildot

array([[22, 50],
       [32, 66]])

In [255]:
hasildot2= m1 @ m2
hasildot2

array([[22, 50],
       [32, 66]])

Kalau kamu punya `m1` dan `m2` seperti tadi, maka **dot product** (perkalian matriks) bisa langsung dilakukan karena ukuran mereka cocok:

- `m1` berukuran **2 × 3**  
- `m2` berukuran **3 × 2**  
- hasilnya akan berukuran **2 × 2**

---

### Contoh kode:
```python
import numpy as np

m1 = np.array([[2, 3, 1],
               [7, 6, 1]])

m2 = np.array([[1, 2],
               [5, 3],
               [1, 1]])

hasil = np.dot(m1, m2)   # atau m1 @ m2
print(hasil)
```

### Output:
```
[[20 13]
 [38 29]]
```

---

📌 Penjelasan perhitungan:
- Baris pertama `m1` × `m2`:
  \[
  [2, 3, 1] \cdot m2 =
  \big[ 2\cdot1 + 3\cdot5 + 1\cdot1,\; 2\cdot2 + 3\cdot3 + 1\cdot1 \big] = [20, 13]
  \]

- Baris kedua `m1` × `m2`:
  \[
  [7, 6, 1] \cdot m2 =
  \big[ 7\cdot1 + 6\cdot5 + 1\cdot1,\; 7\cdot2 + 6\cdot3 + 1\cdot1 \big] = [38, 29]
  \]

---

👉 Jadi hasil dot product adalah matriks 2×2:  
\[
\begin{bmatrix}
20 & 13 \\
38 & 29
\end{bmatrix}
\]

Mau saya tunjukkan juga cara cek **shape** sebelum dan sesudah perkalian biar lebih gampang memahami aturan ukuran matriks?